sonar.projectKey=Les-Chauffagistes_auth-service-back
sonar.projectName=Auth Service Back
sonar.organization=les-chauffagistes

sonar.sources=src,main.py,init.py
sonar.tests=tests
sonar.python.version=3

sonar.python.coverage.reportPaths=coverage.xml

sonar.cpd.exclusions=tests/**